repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^data/
-   repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        name: "yapf"
        args: ["-irp"]
